baseURL: https://artmorse.github.io/
languageCode: en
title: Academic Folio
copyright: Â© Copyright 2024 The Academic Folio Contributors

theme: academic-folio

enableEmoji: true

enableRobotsTXT: true

relativeURLs: true

markup:
  highlight:
    guessSyntax: true
    style: dracula  # syntax highlighting style for markdown code blocks
                    # choose a style from https://xyproto.github.io/splash/docs/all.html

module:
  imports:
  - path: github.com/FortAwesome/Font-Awesome
    mounts:
    - source: svgs
      target: assets/svgs/fontawesome
